package cn.qrq.mapper;

import cn.qrq.springboot.entities.AdminLog;
import cn.qrq.springboot.entities.Employee;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.SelectKey;

@Mapper
public interface MyLogMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     * @param adminLog
     */
    @Insert({
            "insert into log (username, operation,createDate) ",
            "values (#{username,jdbcType=VARCHAR}, #{operation,jdbcType=VARCHAR}, ",
            "#{createDate,jdbcType=TIMESTAMP}) "
})
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(AdminLog adminLog);
}